version: '3.8'

services:
  wallet-api:
    image: wallet-api:latest
    build:
      context: .
      dockerfile: Wallet.Api\Dockerfile
    ports:
      - "5000:80"
    restart: on-failure
    volumes:
      - wallet-data:/app/data

  orderdiscount-api:
    image: orderdiscount-api:latest
    build:
      context: .
      dockerfile: Order.Api\Dockerfile
    ports:
      - "5001:80"
    restart: on-failure
    volumes:
      - order-data:/app/data

  #postgres-db:
  #  image: postgres:latest
  #  environment:
  #    POSTGRES_USER: admin
  #    POSTGRES_PASSWORD: password
  #    POSTGRES_DB: BookLandDB
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - ./SqlScripts.sql:/docker-entrypoint-initdb.d/SqlScripts.sql
  #    - ./db-data/postgres/:/var/lib/postgresql/data/

networks:
  my_network:
    external: true

volumes:
  wallet-data:
  order-data:
