version: '3.8'

services:
  wallet-api:
    image: wallet-api:latest
    build:
      context: .
      dockerfile: Wallet.Api\Dockerfile
    ports:
      - "5000:5000"
    networks:
      - db_network
    depends_on:
      - postgres-db
    restart: on-failure

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BookLandDB
    ports:
      - "5432:5432"
    networks:
      - db_network
    volumes:
      - ./SqlScripts.sql:/docker-entrypoint-initdb.d/SqlScripts.sql
      - ./db-data/postgres/:/var/lib/postgresql/data/

networks:
  db_network:
  
